### ISSUE TITLE
Absolutely not an issue

### ISSUE THREAD

**Issue by stevenart** [saulodias/ionicons-font#1]
Hi,

Sorry to use the "issues" section for this but I'm trying to do what you did with ionicons but for heroicons.com... without much luck. May I ask what tools did you use? I have problems with icomoon.io because of strokes that should be fills (or the other way around) when I upload SVG from heroicons. Any advice?

Thanks for your work !

**Comment by saulodias** [comment]
Hello @stevenart ! Please check out my article on how to [convert your SVG files from stroke to path](https://dev.to/saulodias/convert-svgs-from-stroke-to-path-420j). If you have any questions related to the conversion process, let me know in the comments. I hope this helps.

**Comment by stevenart** [comment]
Thank you!
Have a great day.
